=== joselabs/L2jResourcesH5/L2Ethernity/game/data/xsd/npcs.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="unbounded">
				<xs:element name="npc" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="unbounded">
							<xs:element name="set" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="name" type="xs:string" />
									<xs:attribute name="value" type="xs:string" />
								</xs:complexType>
							</xs:element>
							<xs:element name="ai_params" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="1" maxOccurs="unbounded">
										<xs:element name="set" minOccurs="1" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="name" type="xs:string" />
												<xs:attribute name="value" type="xs:string" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="equip" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="1" maxOccurs="unbounded">
										<xs:element name="rhand" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="itemId" type="xs:integer" />
											</xs:complexType>
										</xs:element>
										<xs:element name="lhand" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="itemId" type="xs:integer" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="faction" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="0" maxOccurs="unbounded">
										<xs:element name="ignore" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="npcId" type="xs:integer" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" type="xs:string" />
									<xs:attribute name="range" type="xs:integer" />
								</xs:complexType>
							</xs:element>
							<xs:element name="teach_classes" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="0" maxOccurs="unbounded">
										<xs:element name="class" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="id" type="xs:integer" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="skills" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="1" maxOccurs="unbounded">
										<xs:element name="skill" minOccurs="1" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="id" type="xs:integer" />
												<xs:attribute name="level" type="xs:integer" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="minions" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="0" maxOccurs="unbounded">
										<xs:element name="random" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence minOccurs="0" maxOccurs="unbounded">
													<xs:element name="minion" minOccurs="0" maxOccurs="unbounded">
														<xs:complexType>
															<xs:attribute name="list" type="xs:string" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="minion" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="npcId" type="xs:integer" />
												<xs:attribute name="count" type="xs:integer" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="absorblist" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="0" maxOccurs="unbounded">
										<xs:element name="absorb" minOccurs="1" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="chance" type="xs:integer" />
												<xs:attribute name="min_level" type="xs:integer" />
												<xs:attribute name="max_level" type="xs:integer" />
												<xs:attribute name="type" type="xs:string" />
												<xs:attribute name="skill" type="xs:string" />
												<xs:attribute name="cursed_chance" type="xs:integer" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="attributes" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="1" maxOccurs="unbounded">
										<xs:element name="attack" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="attribute" type="xs:string" />
												<xs:attribute name="value" type="xs:integer" />
											</xs:complexType>
										</xs:element>
										<xs:element name="defence" minOccurs="1" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="attribute" type="xs:string" />
												<xs:attribute name="value" type="xs:integer" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="rewardlist" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="0" maxOccurs="unbounded">
										<xs:element name="group" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence minOccurs="0" maxOccurs="unbounded">
													<xs:element name="reward" minOccurs="0" maxOccurs="unbounded">
														<xs:complexType>
															<xs:attribute name="itemId" type="xs:integer" />
															<xs:attribute name="min" type="xs:integer" />
															<xs:attribute name="max" type="xs:integer" />
															<xs:attribute name="chance" type="xs:decimal" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="chance" type="xs:decimal" />
											</xs:complexType>
										</xs:element>
										<xs:element name="reward" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="itemId" type="xs:integer" />
												<xs:attribute name="min" type="xs:integer" />
												<xs:attribute name="max" type="xs:integer" />
												<xs:attribute name="chance" type="xs:decimal" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="type" type="xs:string" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="xs:integer" />
						<xs:attribute name="templateId" type="xs:integer" />
						<xs:attribute name="nameEn" type="xs:string" />
						<xs:attribute name="nameRu" type="xs:string" />
						<xs:attribute name="titleEn" type="xs:string" />
						<xs:attribute name="titleRu" type="xs:string" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== joselabs/L2jResourcesH5/L2Ethernity/game/data/stats/npcs/npcs/12600-12699.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/npcs.xsd">
	<npc id="12621" nameRu="Виверна" nameEn="Wyvern" titleRu="" titleEn="">
		<set name="aggroRange" value="0" />
		<set name="ai_type" value="Fighter" />
		<set name="baseAtkRange" value="40" />
		<set name="baseCON" value="43" />
		<set name="baseCritRate" value="4" />
		<set name="baseDEX" value="30" />
		<set name="baseHpMax" value="2444.468" />
		<set name="baseHpRate" value="1" />
		<set name="baseHpReg" value="7.5" />
		<set name="baseINT" value="21" />
		<set name="baseMAtk" value="780" />
		<set name="baseMAtkSpd" value="333" />
		<set name="baseMDef" value="382" />
		<set name="baseMEN" value="25" />
		<set name="baseMpMax" value="1345.8" />
		<set name="baseMpReg" value="2.7" />
		<set name="basePAtk" value="1303" />
		<set name="basePAtkSpd" value="253" />
		<set name="basePDef" value="471" />
		<set name="baseRunSpd" value="170" />
		<set name="baseSTR" value="40" />
		<set name="baseShldDef" value="0" />
		<set name="baseShldRate" value="0" />
		<set name="baseWIT" value="20" />
		<set name="baseWalkSpd" value="80" />
		<set name="collision_height" value="80.0" />
		<set name="collision_radius" value="60.0" />
		<set name="level" value="70" />
		<set name="rewardExp" value="0" />
		<set name="rewardRp" value="0" />
		<set name="rewardSp" value="0" />
		<set name="shots" value="NONE" />
		<set name="texture" value="" />
		<set name="type" value="Monster" />
		<skills>
			<skill id="4416" level="10" />	<!--Dragons-->
			<skill id="4408" level="1" />	<!--HP Increase (1x)-->
			<skill id="4409" level="1" />	<!--MP Increase (1x)-->
			<skill id="4410" level="11" />	<!--Average P. Atk.-->
			<skill id="4411" level="11" />	<!--Average M. Atk.-->
			<skill id="4412" level="11" />	<!--Average P. Def.-->
			<skill id="4413" level="11" />	<!--Average M. Def.-->
			<skill id="4414" level="2" />	<!--Standard Type-->
			<skill id="4415" level="1" />	<!--Bare Hands-->
			<skill id="4121" level="1" />	<!--Summoned Monster Magic Protection-->
			<skill id="4289" level="1" />	<!--Wyvern Breath-->
		</skills>
		<attributes>
			<defence attribute="fire" value="20" />
			<defence attribute="water" value="20" />
			<defence attribute="wind" value="20" />
			<defence attribute="earth" value="20" />
			<defence attribute="holy" value="20" />
			<defence attribute="unholy" value="20" />
		</attributes>
	</npc>
</list>
