=== joselabs/L2jResourcesH5/L2Ethernity/game/data/xsd/quests.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="quest" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="1">
							<xs:element name="level" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="min" type="xs:integer" use="required" />
									<xs:attribute name="max" type="xs:integer" />
								</xs:complexType>
							</xs:element>
							<xs:element name="expirience" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="1" maxOccurs="1">
										<xs:element name="rewardExp" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="rate" type="xs:decimal" />
												<xs:attribute name="val" type="xs:integer" use="required" />
												<xs:attribute name="rateable" type="xs:boolean" use="required" />
											</xs:complexType>
										</xs:element>
										<xs:element name="rewardSp" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="rate" type="xs:decimal" />
												<xs:attribute name="val" type="xs:integer" use="required" />
												<xs:attribute name="rateable" type="xs:boolean" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="droplist" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="1" maxOccurs="1">
										<xs:element name="npc" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence minOccurs="1" maxOccurs="1">
													<xs:element name="item" minOccurs="0" maxOccurs="unbounded">
														<xs:complexType>
															<xs:attribute name="id" type="xs:integer" use="required" />
															<xs:attribute name="rate" type="xs:decimal" />
															<xs:attribute name="min" type="xs:integer" use="required" />
															<xs:attribute name="max" type="xs:integer" />
															<xs:attribute name="chance" type="xs:decimal" use="required" />
															<xs:attribute name="rateable" type="xs:boolean" use="required" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="id" type="xs:positiveInteger" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="add_parameters" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="1" maxOccurs="unbounded">
										<xs:element name="set" minOccurs="1" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="name" type="xs:string" />
												<xs:attribute name="value" type="xs:string" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="rewardlist" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="1" maxOccurs="1">
										<xs:element name="variant" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence minOccurs="1" maxOccurs="1">
													<xs:element name="item" minOccurs="0" maxOccurs="unbounded">
														<xs:complexType>
															<xs:attribute name="id" type="xs:integer" use="required" />
															<xs:attribute name="rate" type="xs:decimal" />
															<xs:attribute name="min" type="xs:integer" use="required" />
															<xs:attribute name="max" type="xs:integer" />
															<xs:attribute name="rateable" type="xs:boolean" use="required" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="id" type="xs:positiveInteger" use="required" />
											</xs:complexType>
										</xs:element>
										<xs:element name="item" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="id" type="xs:integer" use="required" />
												<xs:attribute name="rate" type="xs:decimal" />
												<xs:attribute name="min" type="xs:integer" use="required" />
												<xs:attribute name="max" type="xs:integer" />
												<xs:attribute name="rateable" type="xs:boolean" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="xs:positiveInteger" use="required" />
						<xs:attribute name="nameEn" type="xs:normalizedString" use="required" />
						<xs:attribute name="nameRu" type="xs:normalizedString" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== joselabs/L2jResourcesH5/L2Ethernity/game/data/stats/quests/[10280] Mutated Kaneus - Schuttgart.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/quests.xsd">
	<quest id="10280" nameEn="Mutated Kaneus - Schuttgart" nameRu="Мутант Канеус - Шутгарт">
		<droplist>
			<npc id="18571">
				<item id="13838" min="1" chance="100" rateable="false" /> <!--Venomous Storace's Cellular Tissue-->
			</npc>
			<npc id="18573">
				<item id="13839" min="1" chance="100" rateable="false" /> <!--Kel Bilette's Cellular Tissue-->
			</npc>
		</droplist>
		<rewardlist>
			<item id="57" min="210000" rateable="true" /> <!--Adena-->
		</rewardlist>
	</quest>
</list>

=== joselabs/L2jResourcesH5/L2Ethernity/game/data/stats/quests/[10291] Fire Dragon Destroyer.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/quests.xsd">
	<quest id="10291" nameEn="Fire Dragon Destroyer" nameRu="Убить Огненного Дракона">
		<expirience>
			<rewardExp val="717291" rateable="true" />
			<rewardSp val="77397" rateable="true" />
		</expirience>
		<droplist>
			<npc id="29028">
				<item id="15525" min="1" chance="100" rateable="false" /> <!--Valor Necklace-->
			</npc>
		</droplist>
		<rewardlist>
			<item id="57" min="126549" rateable="true" /> <!--Adena-->
			<item id="8567" min="1" rateable="false" /> <!--Valakas Slayer Circlet-->
		</rewardlist>
	</quest>
</list>

=== joselabs/L2jResourcesH5/L2Ethernity/game/data/stats/quests/[00242] Possessor of a Precious Soul - 2.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/quests.xsd">
	<quest id="242" nameEn="Possessor of a Precious Soul - 2" nameRu="Драгоценная душа, ч. 2">
		<expirience>
			<rewardExp val="455764" rateable="true" />
		</expirience>
		<droplist>
			<npc id="27317">
				<item id="7595" min="1" chance="100" rateable="true" /> <!--Orb of Binding-->
			</npc>
		</droplist>
		<rewardlist>
			<item id="7678" min="1" rateable="false" /> <!--Caradine's Letter-->
		</rewardlist>
	</quest>
</list>

=== joselabs/L2jResourcesH5/L2Ethernity/game/data/stats/quests/[00039] Red-Eyed Invaders.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/quests.xsd">
	<quest id="39" nameEn="Red-Eyed Invaders" nameRu="Красноглазые захватчики">
		<droplist>
			<npc id="20919">
				<item id="7178" min="1" chance="60" rateable="true" /> <!--Black Bone Necklace-->
			</npc>
			<npc id="20920">
				<item id="7178" min="1" chance="60" rateable="true" /> <!--Black Bone Necklace-->
				<item id="7180" min="1" chance="60" rateable="true" /> <!--Incense Pouch-->
			</npc>
			<npc id="20921">
				<item id="7179" min="1" chance="60" rateable="true" /> <!--Red Bone Necklace-->
				<item id="7180" min="1" chance="60" rateable="true" /> <!--Incense Pouch-->
			</npc>
			<npc id="20925">
				<item id="7181" min="1" chance="60" rateable="true" /> <!--Gem of Maille Lizardman-->
			</npc>
		</droplist>
		<rewardlist>
			<item id="6521" min="60" rateable="true" /> <!--Green Colored Lure-->
			<item id="6529" min="1" rateable="false" /> <!--Baby Duck Rod-->
			<item id="6535" min="500" rateable="true" /> <!--Fishing Shot (No-Grade)-->
		</rewardlist>
	</quest>
</list>

=== joselabs/L2jResourcesH5/L2Ethernity/game/data/stats/quests/[00663] Seductive Whispers.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/quests.xsd">
	<quest id="663" nameEn="Seductive Whispers" nameRu="Обольщающий шепот">
		<level min="50" max="85" />
		<droplist>
			<npc id="20674">
				<item id="8766" min="1" chance="80" rateable="true" /> <!--Spirit Bead-->
			</npc>
			<npc id="20678">
				<item id="8766" min="1" chance="80" rateable="true" /> <!--Spirit Bead-->
			</npc>
			<npc id="20954">
				<item id="8766" min="1" chance="80" rateable="true" /> <!--Spirit Bead-->
			</npc>
			<npc id="20955">
				<item id="8766" min="1" chance="80" rateable="true" /> <!--Spirit Bead-->
			</npc>
			<npc id="20956">
				<item id="8766" min="1" chance="80" rateable="true" /> <!--Spirit Bead-->
			</npc>
			<npc id="20957">
				<item id="8766" min="1" chance="80" rateable="true" /> <!--Spirit Bead-->
			</npc>
			<npc id="20958">
				<item id="8766" min="1" chance="80" rateable="true" /> <!--Spirit Bead-->
			</npc>
			<npc id="20959">
				<item id="8766" min="1" chance="80" rateable="true" /> <!--Spirit Bead-->
			</npc>
			<npc id="20960">
				<item id="8766" min="1" chance="80" rateable="true" /> <!--Spirit Bead-->
			</npc>
			<npc id="20961">
				<item id="8766" min="1" chance="80" rateable="true" /> <!--Spirit Bead-->
			</npc>
			<npc id="20962">
				<item id="8766" min="1" chance="80" rateable="true" /> <!--Spirit Bead-->
			</npc>
			<npc id="20974">
				<item id="8766" min="1" chance="80" rateable="true" /> <!--Spirit Bead-->
			</npc>
			<npc id="20975">
				<item id="8766" min="1" chance="80" rateable="true" /> <!--Spirit Bead-->
			</npc>
			<npc id="20976">
				<item id="8766" min="1" chance="80" rateable="true" /> <!--Spirit Bead-->
			</npc>
			<npc id="20996">
				<item id="8766" min="1" chance="80" rateable="true" /> <!--Spirit Bead-->
			</npc>
			<npc id="20997">
				<item id="8766" min="1" chance="80" rateable="true" /> <!--Spirit Bead-->
			</npc>
			<npc id="20998">
				<item id="8766" min="1" chance="80" rateable="true" /> <!--Spirit Bead-->
			</npc>
			<npc id="20999">
				<item id="8766" min="1" chance="80" rateable="true" /> <!--Spirit Bead-->
			</npc>
			<npc id="21001">
				<item id="8766" min="1" chance="80" rateable="true" /> <!--Spirit Bead-->
			</npc>
			<npc id="21002">
				<item id="8766" min="1" chance="80" rateable="true" /> <!--Spirit Bead-->
			</npc>
			<npc id="21006">
				<item id="8766" min="1" chance="80" rateable="true" /> <!--Spirit Bead-->
			</npc>
			<npc id="21007">
				<item id="8766" min="1" chance="80" rateable="true" /> <!--Spirit Bead-->
			</npc>
			<npc id="21008">
				<item id="8766" min="1" chance="80" rateable="true" /> <!--Spirit Bead-->
			</npc>
			<npc id="21009">
				<item id="8766" min="1" chance="80" rateable="true" /> <!--Spirit Bead-->
			</npc>
			<npc id="21010">
				<item id="8766" min="1" chance="80" rateable="true" /> <!--Spirit Bead-->
			</npc>
		</droplist>
		<rewardlist>
			<variant id="1">
				<item id="57" min="40000" rateable="false" /> <!--Adena-->
			</variant>
			<variant id="2">
				<item id="57" min="80000" rateable="false" /> <!--Adena-->
			</variant>
			<variant id="3">
				<item id="57" min="110000" rateable="false" /> <!--Adena-->
				<item id="955" min="1" rateable="true" /> <!--Scroll: Enchant Weapon (D-Grade)-->
			</variant>
			<variant id="4">
				<item id="57" min="199000" rateable="false" /> <!--Adena-->
				<item id="951" min="1" rateable="true" /> <!--Scroll: Enchant Weapon (C-Grade)-->
			</variant>
			<variant id="5"> <!--Random reward-->
				<item id="4963" min="1" rateable="true" /> <!--Recipe: Great Sword (60%)-->
				<item id="4966" min="1" rateable="true" /> <!--Recipe: Keshanberk (60%)-->
				<item id="4967" min="1" rateable="true" /> <!--Recipe: Sword of Valhalla (60%)-->
				<item id="4968" min="1" rateable="true" /> <!--Recipe: Kris (60%)-->
				<item id="5001" min="1" rateable="true" /> <!--Recipe: Lance (60%)-->
				<item id="5003" min="1" rateable="true" /> <!--Recipe: Art of Battle Axe (60%)-->
				<item id="5004" min="1" rateable="true" /> <!--Recipe: Staff of Evil Spirits (60%)-->
				<item id="5005" min="1" rateable="true" /> <!--Recipe: Demon's Dagger (60%)-->
				<item id="5006" min="1" rateable="true" /> <!--Recipe: Bellion Cestus (60%)-->
				<item id="5007" min="1" rateable="true" /> <!--Recipe: Bow of Peril (60%)-->
			</variant>
			<variant id="6"> <!--Random reward-->
				<item id="4101" min="1" rateable="true" /> <!--Zubei's Shield Fragment-->
				<item id="4107" min="1" rateable="true" /> <!--Keshanberk Blade-->
				<item id="4108" min="1" rateable="true" /> <!--Sword of Valhalla Blade-->
				<item id="4109" min="1" rateable="true" /> <!--Kris Edge-->
				<item id="4115" min="1" rateable="true" /> <!--Lance Blade-->
				<item id="4117" min="1" rateable="true" /> <!--Art of Battle Axe Blade-->
				<item id="4118" min="1" rateable="true" /> <!--Evil Spirit Head-->
				<item id="4119" min="1" rateable="true" /> <!--Demon's Dagger Edge-->
				<item id="4120" min="1" rateable="true" /> <!--Bellion Cestus Edge-->
				<item id="4121" min="1" rateable="true" /> <!--Bow of Peril Shaft-->
			</variant>
			<variant id="7">
				<item id="57" min="1284000" rateable="false" /> <!--Adena-->
				<item id="947" min="2" rateable="true" /> <!--Scroll: Enchant Weapon (B-Grade)-->
				<item id="948" min="2" rateable="true" /> <!--Scroll: Enchant Armor (B-Grade)-->
			</variant>
			<variant id="8">
				<item id="57" min="2384000" rateable="false" /> <!--Adena-->
				<item id="729" min="1" rateable="true" /> <!--Scroll: Enchant Weapon (A-Grade)-->
				<item id="730" min="2" rateable="true" /> <!--Scroll: Enchant Armor (A-Grade)-->
			</variant>
			<variant id="9"> <!--Reward with 6 variant-->
				<item id="57" min="675000" rateable="false" /> <!--Adena-->
			</variant>
			<variant id="10"> <!--Reward with 5 variant-->
				<item id="57" min="388000" rateable="false" /> <!--Adena-->
			</variant>
		</rewardlist>
	</quest>
</list>

=== joselabs/L2jResourcesH5/L2Ethernity/game/data/stats/quests/[00186] Contract Execution.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/quests.xsd">
	<quest id="186" nameEn="Contract Execution" nameRu="Выполнение условий договора">
		<expirience>
			<rewardExp val="285935" rateable="true" />
			<rewardSp val="18711" rateable="true" />
		</expirience>
		<droplist>
			<npc id="20577">
				<item id="10367" min="1" chance="40" rateable="true" /> <!--Leto Lizardman Accessory-->
			</npc>
			<npc id="20578">
				<item id="10367" min="1" chance="44" rateable="true" /> <!--Leto Lizardman Accessory-->
			</npc>
			<npc id="20579">
				<item id="10367" min="1" chance="46" rateable="true" /> <!--Leto Lizardman Accessory-->
			</npc>
			<npc id="20580">
				<item id="10367" min="1" chance="88" rateable="true" /> <!--Leto Lizardman Accessory-->
			</npc>
			<npc id="20581">
				<item id="10367" min="1" chance="50" rateable="true" /> <!--Leto Lizardman Accessory-->
			</npc>
			<npc id="20582">
				<item id="10367" min="1" chance="100" rateable="true" /> <!--Leto Lizardman Accessory-->
			</npc>
		</droplist>
		<rewardlist>
			<item id="57" min="105083" rateable="true" /> <!--Adena-->
		</rewardlist>
	</quest>
</list>

=== joselabs/L2jResourcesH5/L2Ethernity/game/data/stats/quests/[00603] Daimon the White-Eyed - Part 1.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/quests.xsd">
	<quest id="603" nameEn="Daimon the White-Eyed - Part 1" nameRu="Белоглазый Демон - ч. 1">
		<droplist>
			<npc id="21297">
				<item id="7190" min="1" chance="50" rateable="true" /> <!--Evil Spirit of Darkness-->
			</npc>
			<npc id="21299">
				<item id="7190" min="1" chance="52" rateable="true" /> <!--Evil Spirit of Darkness-->
			</npc>
			<npc id="21304">
				<item id="7190" min="1" chance="67" rateable="true" /> <!--Evil Spirit of Darkness-->
			</npc>
		</droplist>
		<rewardlist>
			<item id="7192" min="1" rateable="false" /> <!--Unfinished Summon Crystal-->
		</rewardlist>
	</quest>
</list>
