=== joselabs/L2jResourcesH5/L2Ethernity/game/data/xsd/reflection.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="instance" maxOccurs="9999" minOccurs="0">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="1">
							<xs:element name="level" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:attribute name="min" type="xs:positiveInteger" use="required" />
									<xs:attribute name="max" type="xs:positiveInteger" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="party" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:attribute name="min" type="xs:positiveInteger" use="required" />
									<xs:attribute name="max" type="xs:positiveInteger" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="allowSummon" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:attribute name="val" type="xs:boolean" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="return" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:attribute name="x" type="xs:integer" use="required" />
									<xs:attribute name="y" type="xs:integer" use="required" />
									<xs:attribute name="z" type="xs:integer" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="teleport" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="x" type="xs:integer" use="required" />
									<xs:attribute name="y" type="xs:integer" use="required" />
									<xs:attribute name="z" type="xs:integer" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="remove" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:attribute name="itemId" type="xs:integer" use="required" />
									<xs:attribute name="count" type="xs:integer" use="required" />
									<xs:attribute name="necessary" type="xs:boolean" use="required" />
									<xs:attribute name="type">
										<xs:simpleType>
											<xs:restriction base="xs:token">
												<xs:enumeration value="NONE" />
												<xs:enumeration value="LEADER" />
												<xs:enumeration value="ALL" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="give" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:attribute name="itemId" type="xs:integer" use="required" />
									<xs:attribute name="count" type="xs:integer" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="quest" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:attribute name="name" type="xs:normalizedString" use="required" />
									<xs:attribute name="type">
										<xs:simpleType>
											<xs:restriction base="xs:token">
												<xs:enumeration value="STARTED" />
												<xs:enumeration value="COMPLETED" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="isPvP" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:attribute name="val" type="xs:boolean" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="showTimer" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:attribute name="val" type="xs:boolean" use="required" />
									<xs:attribute name="increase" type="xs:boolean" />
									<xs:attribute name="text" type="xs:normalizedString" />
								</xs:complexType>
							</xs:element>
							<xs:element name="geodata" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:attribute name="mapX" type="xs:integer" use="required" />
									<xs:attribute name="mapY" type="xs:integer" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="reenter" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="reset" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="day">
													<xs:simpleType>
														<xs:restriction base="xs:token">
															<xs:enumeration value="Monday" />
															<xs:enumeration value="Tuesday" />
															<xs:enumeration value="Wednesday" />
															<xs:enumeration value="Thursday" />
															<xs:enumeration value="Friday" />
															<xs:enumeration value="Saturday" />
															<xs:enumeration value="Sunday" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="time" type="xs:long" />
												<xs:attribute name="hour" type="xs:positiveInteger" />
												<xs:attribute name="minute" type="xs:positiveInteger" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="setUponEntry" type="xs:boolean" use="required" />
									<xs:attribute name="sharedReuseGroup" type="xs:integer" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="add_parameters" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="1" maxOccurs="unbounded">
										<xs:element name="set" minOccurs="1" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="name" type="xs:string" />
												<xs:attribute name="value" type="xs:string" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="doorlist" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence minOccurs="1" maxOccurs="1">
										<xs:element name="door" minOccurs="1" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="doorId" type="xs:positiveInteger" use="required" />
												<xs:attribute name="default_status">
													<xs:simpleType>
														<xs:restriction base="xs:token">
															<xs:enumeration value="open" />
															<xs:enumeration value="close" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="random_time" type="xs:integer" />
												<xs:attribute name="open_time" type="xs:integer" />
												<xs:attribute name="close_time" type="xs:integer" />
												<xs:attribute name="level" type="xs:nonNegativeInteger" />
												<xs:attribute name="open_method" type="xs:nonNegativeInteger" />
												<xs:attribute name="targetable" type="xs:boolean" />
												<xs:attribute name="check_collision" type="xs:boolean" />
												<xs:attribute name="clanhall_id" type="xs:positiveInteger" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="spawns" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence minOccurs="1" maxOccurs="unbounded">
										<xs:element name="group" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="name" type="xs:normalizedString" use="required" />
												<xs:attribute name="spawned" type="xs:boolean" />
											</xs:complexType>
										</xs:element>
										<xs:element name="spawn" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence minOccurs="1" maxOccurs="1">
													<xs:element name="coords" minOccurs="1" maxOccurs="unbounded">
														<xs:complexType>
															<xs:attribute name="loc" type="xs:string" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="mobId" type="xs:string" use="required" />
												<xs:attribute name="count" type="xs:positiveInteger" />
												<xs:attribute name="respawn" type="xs:integer" />
												<xs:attribute name="respawnRnd" type="xs:integer" />
												<xs:attribute name="type" type="xs:string" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="xs:positiveInteger" use="required" />
						<xs:attribute name="name" type="xs:normalizedString" use="required" />
						<xs:attribute name="maxChannels" type="xs:positiveInteger" />
						<xs:attribute name="collapseIfEmpty" type="xs:integer" />
						<xs:attribute name="timelimit" type="xs:integer" />
						<xs:attribute name="dispelBuffs" type="xs:boolean" />
						<xs:attribute name="respawn" type="xs:integer" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== joselabs/L2jResourcesH5/L2Ethernity/game/data/stats/instances/[110] Seed of Destruction.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/reflection.xsd">
	<instance id="110" name="Seed of Destruction" maxChannels="3" collapseIfEmpty="20" timelimit="130" dispelBuffs="false">
		<level min="75" max="85" />
		<party min="36" max="45" />
		<allowSummon val="false" />
		<return x="-248376" y="250440" z="4344" />
		<teleport x="-242738" y="219995" z="-9984" />
		<geodata mapX="12" mapY="24" />
		<reenter setUponEntry="false" sharedReuseGroup="0">
			<reset day="Wednesday" hour="6" minute="30" />
			<reset day="Saturday" hour="6" minute="30" />
		</reenter>
		<doorlist>
			<door doorId="12240001" />
			<door doorId="12240002" />
			<door doorId="12240003" />
			<door doorId="12240004" />
			<door doorId="12240005" />
			<door doorId="12240006" />
			<door doorId="12240007" />
			<door doorId="12240008" />
			<door doorId="12240009" />
			<door doorId="12240010" />
			<door doorId="12240011" />
			<door doorId="12240012" />
			<door doorId="12240013" />
			<door doorId="12240014" />
			<door doorId="12240015" />
			<door doorId="12240016" />
			<door doorId="12240017" />
			<door doorId="12240018" />
			<door doorId="12240019" />
			<door doorId="12240020" />
			<door doorId="12240021" />
			<door doorId="12240022" />
			<door doorId="12240023" />
			<door doorId="12240024" />
			<door doorId="12240025" />
			<door doorId="12240026" />
			<door doorId="12240027" />
			<door doorId="12240028" />
			<door doorId="12240029" />
			<door doorId="12240030" />
			<door doorId="12240031" />
		</doorlist>
	</instance>
</list>

=== joselabs/L2jResourcesH5/L2Ethernity/game/data/stats/instances/[126] Great Warrior's Mounted Troop.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/reflection.xsd">
	<instance id="126" name="Chamblain's Mounted Troop" maxChannels="5" collapseIfEmpty="10" timelimit="20" dispelBuffs="true">
		<level min="75" max="85" />
		<party min="2" max="9" />
		<allowSummon val="false" />
		<return x="-248536" y="250072" z="4337" />
		<teleport x="-242754" y="219982" z="-10011" />
		<showTimer val="true" />
		<geodata mapX="12" mapY="24" />
		<reenter setUponEntry="true" sharedReuseGroup="6">
			<reset hour="6" minute="30" />
		</reenter>
		<doorlist>
			<door doorId="12240001" />
			<door doorId="12240002" />
		</doorlist>
		<spawns>
			<spawn mobId="18703" type="point" respawn="0">
				<coords loc="-238320, 219983, -10112, 0" />
			</spawn>
			<spawn mobId="18786" type="point" respawn="0">
				<coords loc="-239504, 219984, -10112, 32767" />
			</spawn>
			<spawn mobId="18783" type="point" respawn="0">
				<coords loc="-239834, 220544, -10135, 49151" />
			</spawn>
			<spawn mobId="18783" type="point" respawn="0">
				<coords loc="-239617, 219989, -10144, 32523" />
			</spawn>
			<spawn mobId="18783" type="point" respawn="0">
				<coords loc="-239834, 219428, -10135, 15910" />
			</spawn>
			<spawn mobId="18784" type="point" respawn="0">
				<coords loc="-240417, 219419, -10135, 15640" />
			</spawn>
			<spawn mobId="18784" type="point" respawn="0">
				<coords loc="-240418, 220540, -10135, 48714" />
			</spawn>
			<spawn mobId="18787" type="point" respawn="0">
				<coords loc="-240130, 220722, -10144, 48319" />
			</spawn>
			<spawn mobId="18787" type="point" respawn="0">
				<coords loc="-240120, 219208, -10144, 15640" />
			</spawn>
			<spawn mobId="18790" type="point" respawn="0">
				<coords loc="-239625, 219665, -10144, 32347" />
			</spawn>
			<spawn mobId="18790" type="point" respawn="0">
				<coords loc="-239611, 220311, -10144, 32456" />
			</spawn>
			<spawn mobId="18784" type="point" respawn="0">
				<coords loc="-238545, 219906, -10144, 30049" />
			</spawn>
			<spawn mobId="18784" type="point" respawn="0">
				<coords loc="-238532, 220099, -10144, 30429" />
			</spawn>
			<spawn mobId="18787" type="point" respawn="0">
				<coords loc="-238687, 220537, -10135, 48457" />
			</spawn>
			<spawn mobId="18787" type="point" respawn="0">
				<coords loc="-238683, 219426, -10135, 15551" />
			</spawn>
			<spawn mobId="18790" type="point" respawn="0">
				<coords loc="-238686, 219172, -10144, 15427" />
			</spawn>
			<spawn mobId="18790" type="point" respawn="0">
				<coords loc="-238685, 220797, -10144, 48775" />
			</spawn>
			<spawn mobId="18785" type="point" respawn="0">
				<coords loc="-238522, 219527, -10144, 16204" />
			</spawn>
			<spawn mobId="18785" type="point" respawn="0">
				<coords loc="-238884, 219515, -10144, 15369" />
			</spawn>
			<spawn mobId="18785" type="point" respawn="0">
				<coords loc="-238884, 219986, -10144, 32871" />
			</spawn>
		</spawns>
	</instance>
</list>

=== joselabs/L2jResourcesH5/L2Ethernity/game/data/stats/instances/[079] Kamaloka, Labyrinth of the Abyss.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/reflection.xsd">
	<instance id="79" name="Kamaloka Labyrinth of the Abyss (Level 81)" maxChannels="10" collapseIfEmpty="10" timelimit="45" dispelBuffs="true">
		<level min="76" max="85" />
		<party min="2" max="9" />
		<allowSummon val="false" />
		<return x="42767" y="-48016" z="-800" />
		<teleport x="-10700" y="-174882" z="-10936" />
		<reenter setUponEntry="false" sharedReuseGroup="4">
			<reset hour="6" minute="30" />
		</reenter>
	</instance>
</list>

=== joselabs/L2jResourcesH5/L2Ethernity/game/data/stats/instances/[062] Kamaloka, Hall of the Abyss.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/reflection.xsd">
	<instance id="62" name="Kamaloka, Hall of the Abyss (Level 36) PC Cafe" maxChannels="10" collapseIfEmpty="10" timelimit="30" dispelBuffs="false">
		<level min="31" max="41" />
		<party min="2" max="6" />
		<allowSummon val="false" />
		<return x="18181" y="145987" z="-3104" />
		<teleport x="-74825" y="-214194" z="-7889" />
		<remove itemId="-100" count="2500" necessary="true" type="ALL" />
		<reenter setUponEntry="false" sharedReuseGroup="3">
			<reset hour="6" minute="30" />
		</reenter>
	</instance>
</list>

=== joselabs/L2jResourcesH5/L2Ethernity/game/data/stats/instances/[129] Delusion Chamber, Southern Seal.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/reflection.xsd">
	<instance id="129" name="Delusion Chamber, Southern Seal" maxChannels="20" collapseIfEmpty="0" timelimit="40" dispelBuffs="false">
		<level min="80" max="85" />
		<party min="2" max="9" />
		<allowSummon val="false" />
		<add_parameters>
			<set name="bossRoomChance" value="10" />
		</add_parameters>
		<spawns>
			<!-- Room 1 -->
			<spawn mobId="22708" type="point" respawn="25">
				<coords loc="-122263 -208129 -6720 0" />
			</spawn>
			<spawn mobId="22708" type="point" respawn="25">
				<coords loc="-122602 -207637 -6720 0" />
			</spawn>
			<spawn mobId="22709" type="point" respawn="25">
				<coords loc="-122536 -208049 -6720 0" />
			</spawn>
			<spawn mobId="22710" type="point" respawn="25">
				<coords loc="-122277 -207829 -6720 0" />
			</spawn>
			<spawn mobId="32674" type="point" respawn="0">
				<coords loc="-122368 -207920 -6720 0" />
			</spawn>
			<!-- Room 2 -->
			<spawn mobId="22708" type="point" respawn="25">
				<coords loc="-122141 -207152 -6720 0" />
			</spawn>
			<spawn mobId="22710" type="point" respawn="25">
				<coords loc="-122286 -207070 -6720 0" />
			</spawn>
			<spawn mobId="22710" type="point" respawn="25">
				<coords loc="-122597 -206876 -6720 0" />
			</spawn>
			<spawn mobId="22712" type="point" respawn="25">
				<coords loc="-122507 -207233 -6720 0" />
			</spawn>
			<spawn mobId="32675" type="point" respawn="0">
				<coords loc="-122368 -207040 -6720 0" />
			</spawn>
			<!-- Room 3 -->
			<spawn mobId="18817" type="point" respawn="30">
				<coords loc="-122368 -209064 -6720 0" />
			</spawn>
			<spawn mobId="22708" type="point" respawn="30">
				<coords loc="-122328 -209482 -6720 0" />
			</spawn>
			<spawn mobId="22708" type="point" respawn="30">
				<coords loc="-122533 -208964 -6720 0" />
			</spawn>
			<spawn mobId="22708" type="point" respawn="30">
				<coords loc="-122166 -209179 -6720 0" />
			</spawn>
			<spawn mobId="22709" type="point" respawn="30">
				<coords loc="-122099 -209284 -6720 0" />
			</spawn>
			<spawn mobId="22712" type="point" respawn="30">
				<coords loc="-122586 -209070 -6720 0" />
			</spawn>
			<spawn mobId="22712" type="point" respawn="30">
				<coords loc="-122328 -209620 -6720 0" />
			</spawn>
			<spawn mobId="22717" type="point" respawn="30">
				<coords loc="-122156 -209668 -6720 0" />
			</spawn>
			<spawn mobId="22717" type="point" respawn="30">
				<coords loc="-122615 -209656 -6720 0" />
			</spawn>
			<spawn mobId="22718" type="point" respawn="30">
				<coords loc="-122582 -209530 -6720 0" />
			</spawn>
			<spawn mobId="22718" type="point" respawn="30">
				<coords loc="-122471 -208993 -6720 0" />
			</spawn>
			<spawn mobId="32676" type="point" respawn="0">
				<coords loc="-122368 -209216 -6720 0" />
			</spawn>
			<!-- Room 4 -->
			<spawn mobId="22708" type="point" respawn="30">
				<coords loc="-121474 -207448 -6720 0" />
			</spawn>
			<spawn mobId="22708" type="point" respawn="30">
				<coords loc="-121238 -206920 -6720 0" />
			</spawn>
			<spawn mobId="22709" type="point" respawn="30">
				<coords loc="-121398 -207631 -6720 0" />
			</spawn>
			<spawn mobId="22711" type="point" respawn="30">
				<coords loc="-121429 -207218 -6720 0" />
			</spawn>
			<spawn mobId="22712" type="point" respawn="30">
				<coords loc="-121666 -207674 -6720 0" />
			</spawn>
			<spawn mobId="22715" type="point" respawn="30">
				<coords loc="-121202 -206870 -6720 0" />
			</spawn>
			<spawn mobId="22715" type="point" respawn="30">
				<coords loc="-121429 -206783 -6720 0" />
			</spawn>
			<spawn mobId="32677" type="point" respawn="0">
				<coords loc="-121456 -207456 -6720 0" />
			</spawn>
			<!-- Room 5 -->
			<spawn mobId="25692" type="point" respawn="0">
				<coords loc="-121292 -208690 -6720 0" />
			</spawn>
			<spawn mobId="32678" type="point" respawn="0">
				<coords loc="-121440 -209104 -6720 0" />
			</spawn>
		</spawns>
	</instance>
</list>

=== joselabs/L2jResourcesH5/L2Ethernity/game/data/stats/instances/[147] Grassy Arena.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/reflection.xsd">
	<instance id="147" name="Olympiad Grassy Arena" maxChannels="40" collapseIfEmpty="-1" timelimit="0" dispelBuffs="true">
		<level min="1" max="85" />
		<party min="1" max="1" />
		<geodata mapX="17" mapY="10" />
		<doorlist>
			<door doorId="17100001" />
			<door doorId="17100002" />
		</doorlist>
		<spawns>
			<spawn mobId="36402" type="point" respawn="60">
				<coords loc="-89400 -252843 -3341 0" />
			</spawn>
			<spawn mobId="36402" type="point" respawn="60">
				<coords loc="-86763 -252843 -3341 0" />
			</spawn>
		</spawns>
	</instance>
</list>
