=== joselabs/L2jResourcesH5/L2Ethernity/game/data/xsd/spawn.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="unbounded">
				<xs:element name="spawn" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="unbounded">
							<xs:element name="debug" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:attribute name="name" type="xs:string" />
									<xs:attribute name="val" type="xs:string" />
								</xs:complexType>
							</xs:element>
							<xs:element name="point" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:attribute name="x" type="xs:integer" />
									<xs:attribute name="y" type="xs:integer" />
									<xs:attribute name="z" type="xs:integer" />
									<xs:attribute name="h" type="xs:integer" />
								</xs:complexType>
							</xs:element>
							<xs:element name="npc" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="1" maxOccurs="unbounded">
										<xs:element name="set" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="name" type="xs:string" />
												<xs:attribute name="value" type="xs:string" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="id" type="xs:integer" />
									<xs:attribute name="count" type="xs:integer" />
									<xs:attribute name="respawn" type="xs:integer" />
									<xs:attribute name="respawn_random" type="xs:integer" />
									<xs:attribute name="respawn_pattern" type="xs:string" />
								</xs:complexType>
							</xs:element>
							<xs:element name="territory" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="1" maxOccurs="unbounded">
										<xs:element name="add" minOccurs="1" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="x" type="xs:integer" />
												<xs:attribute name="y" type="xs:integer" />
												<xs:attribute name="zmin" type="xs:integer" />
												<xs:attribute name="zmax" type="xs:integer" />
											</xs:complexType>
										</xs:element>
										<xs:element name="banned_territory" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence minOccurs="1" maxOccurs="unbounded">
													<xs:element name="add" minOccurs="1" maxOccurs="unbounded">
														<xs:complexType>
															<xs:attribute name="x" type="xs:integer" />
															<xs:attribute name="y" type="xs:integer" />
															<xs:attribute name="zmin" type="xs:integer" />
															<xs:attribute name="zmax" type="xs:integer" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="count" type="xs:integer" />
						<xs:attribute name="respawn" type="xs:integer" />
						<xs:attribute name="respawn_random" type="xs:integer" />
						<xs:attribute name="respawn_pattern" type="xs:string" />
						<xs:attribute name="period_of_day" type="xs:normalizedString" />
						<xs:attribute name="group" type="xs:normalizedString" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== joselabs/L2jResourcesH5/L2Ethernity/game/data/stats/npcs/spawns/15_25.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/spawn.xsd">
	<spawn count="1" respawn="60" respawn_random="0" period_of_day="none"> 
	<debug name="territory_name" val="15_25 [point-001]" />
		<point x="-149649" y="255028" z="-80" h="16384" />
		<npc id="32614" /><!--Lamcedas-->
	</spawn>
	<spawn count="1" respawn="60" respawn_random="0" period_of_day="none"> 
	<debug name="territory_name" val="15_25 [point-002]" />
		<point x="-148656" y="253841" z="-184" h="24576" />
		<npc id="32616" /><!--Mine-->
	</spawn>
	<spawn count="1" respawn="60" respawn_random="0" period_of_day="none"> 
	<debug name="territory_name" val="15_25 [point-003]" />
		<point x="-149360" y="252936" z="-136" h="16384" />
		<npc id="32609" /><!--Airship Controller-->
	</spawn>
	<spawn count="1" respawn="60" respawn_random="0" period_of_day="none">
	<debug name="territory_name" val="15_25 [point-004]" />
		<point x="-149484" y="253680" z="-184" h="16384" />
		<npc id="32564" /><!--Papiku-->
	</spawn>
	<spawn count="1" respawn="60" respawn_random="0" period_of_day="none">
	<debug name="territory_name" val="15_25 [point-005]" />
		<point x="-149235" y="253680" z="-184" h="16384" />
		<npc id="32565" /><!--Felix-->
	</spawn>
	<spawn count="1" respawn="60" respawn_random="0" period_of_day="none">
	<debug name="territory_name" val="15_25 [point-006]" />
		<point x="-149067" y="255028" z="-80" h="23225" />
		<npc id="32615" /><!--Ishuma-->
	</spawn>
	<spawn count="1" respawn="60" respawn_random="0" period_of_day="none">
	<debug name="territory_name" val="15_25 [point-007]" />
		<point x="-148777" y="254544" z="-186" h="37690" />
		<npc id="32628" /><!--Wharf Patrol-->
	</spawn>
	<spawn count="1" respawn="60" respawn_random="0" period_of_day="none">
	<debug name="territory_name" val="15_25 [point-008]" />
		<point x="-148804" y="254521" z="-187" h="42005" />
		<npc id="32628" /><!--Wharf Patrol-->
	</spawn>
	<spawn count="1" respawn="60" respawn_random="0" period_of_day="none"> 
	<debug name="territory_name" val="15_25 [point-009]" />
		<point x="-149929" y="254543" z="-187" h="50030" />
		<npc id="32629" /><!--Wharf Patrol-->
	</spawn>
	<spawn count="1" respawn="60" respawn_random="0" period_of_day="none"> 
	<debug name="territory_name" val="15_25 [point-010]" />
		<point x="-149909" y="254506" z="-187" h="28583" />
		<npc id="32629" /><!--Wharf Patrol-->
	</spawn>
</list>
